server:
  port: 8091
#mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test-hibernate?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    hikari:

  # Specify the DBMS
  jpa:
    database: MYSQL
    show-sql: true   # Show or not log for each sql query
    hibernate:
      ddl-auto: update   # Hibernate ddl auto (create, create-drop, update)
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy  # 定义HibernateO/R映射字段的命名策略
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQL5Dialect   # 数据库方言
