server:
  port: 80
#jdbc
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heima29?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
#mybatis
mybatis:
  type-aliases-package: cn.speed.demo.jdbc.pojo
