server:
  port: 80
#jdbc
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/heima29?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
  thymeleaf:
    cache: false    #关闭缓存
# mybatis 别名扫描
mybatis:
  type-aliases-package: cn.jxq.demo.pojo
  #mapper-locations: classpath:mappers/*.xml   # mapper.xml文件位置,如果没有映射文件，请注释掉

logging:
  level:
   cn.jxq.demo:
    debug



